#!/usr/bin/env bash

####--------------------------------####
#--# Author:   by Umbrellla777      #--#
#--# Telegram: @Umbrellla_l         #--#
#--# VK:       @Umbrellla777        #--#
####--------------------------------####

# Run
clear
cd Umbrellla777-bot-ENG-
python3 main.py $1 $2
